import { LeftSkull, Moon, RightSkull, Sun } from "@/components/corner-vectors";
import { captainHowdy } from "@/fonts";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
   title: "Aneeq Tahir",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`bg-neutral-800 dark:text-gray-300  ${captainHowdy.className}`}
         >
            <Sun className="fixed dark:fill-neutral-800 fill-[#F9F4DA] top-0 left-0 w-28 sm:w-[20%] h-auto" />
            <Moon className="fixed top-0 dark:fill-neutral-800 fill-[#F9F4DA] right-0 w-28 sm:w-[20%] h-auto" />
            {children}
            <LeftSkull
               bg="dark:fill-neutral-800 fill-[#F9F4DA]"
               className="fixed bottom-0 left-0 w-28 sm:w-[20%] h-auto"
            />
            <RightSkull
               bg="dark:fill-neutral-800 fill-[#F9F4DA]"
               className="fixed bottom-0 right-0 w-28 sm:w-[20%] h-auto"
            />
         </body>
      </html>
   );
}
